# Generated by Django 3.0.5 on 2020-04-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Chucvu',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Linhvuc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Point',
            field=models.IntegerField(default=0),
        ),
    ]
