# Generated by Django 3.0.5 on 2020-04-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200424_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Birthday',
            field=models.DateField(auto_now=True),
        ),
    ]
