# Generated by Django 3.0.5 on 2020-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200424_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=200)),
                ('Code', models.TextField()),
                ('Date', models.DateTimeField(auto_now=True)),
                ('User', models.CharField(default='', max_length=200)),
                ('Like', models.IntegerField(default=0)),
                ('Unlike', models.IntegerField(default=0)),
            ],
        ),
    ]
