# Generated by Django 3.0.5 on 2020-04-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='Img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
