# Generated by Django 3.0.5 on 2020-04-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
    ]
