# Generated by Django 3.0.5 on 2020-04-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_thongbao'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongbao',
            name='id_key',
            field=models.IntegerField(default=1),
        ),
    ]
