# Generated by Django 3.0.5 on 2020-04-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_thongbao_id_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThongBao',
        ),
    ]
