# Generated by Django 3.0.5 on 2020-04-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200428_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='Like',
            field=models.IntegerField(default=1),
        ),
    ]
