# Generated by Django 3.0.5 on 2020-04-29 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_poll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
