# Generated by Django 3.0.5 on 2020-04-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Thongbao',
            field=models.TextField(default='Không có thông báo'),
        ),
    ]
