# Generated by Django 3.0.5 on 2020-04-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200429_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tieude', models.CharField(default='', max_length=200)),
                ('Noidung1', models.TextField(default='')),
                ('Code1', models.TextField(default='')),
                ('Noidung2', models.TextField(default='')),
                ('Code2', models.TextField(default='')),
                ('Noidung3', models.TextField(default='')),
                ('Code3', models.TextField(default='')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('User', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='code',
            name='Loai',
            field=models.CharField(default='Chưa có', max_length=200),
        ),
    ]
