# Generated by Django 3.0.5 on 2020-05-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200430_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='script',
        ),
    ]
