# Generated by Django 3.0.5 on 2020-05-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_comment_share_sharecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharecode',
            name='User',
            field=models.CharField(default='', max_length=200),
        ),
    ]
