# Generated by Django 3.0.5 on 2020-05-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_sharecode_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='hocvien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hovaten', models.CharField(default='No name', max_length=200)),
                ('namsinh', models.IntegerField(default=2010)),
                ('chuyencan', models.IntegerField(default=0)),
                ('diem_baihoc', models.IntegerField(default=0)),
                ('diem_kiemtratuan', models.IntegerField(default=0)),
                ('diem_kiemtrathang', models.IntegerField(default=0)),
                ('diem_ketthuc', models.IntegerField(default=0)),
                ('tongdiem', models.IntegerField(default=0)),
            ],
        ),
    ]
