# Generated by Django 3.0.5 on 2020-05-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_hocvien'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocvien',
            name='chuthich',
            field=models.CharField(default='Chưa có điểm mới', max_length=999999),
        ),
    ]
